### ISSUE TITLE
Getting a new error on working code:  Module "./connection.ts" has already exported a member named 'RedisConnectOptions'.

### ISSUE THREAD

**Issue by reselbob** [denolib/deno-redis#106]
Hi:

When I run my tests a completely refresh my Deno cache in order to make sure I get all the latest libraries.

Today code that ran fine a week ago is erroring as follows

```typescript
TS2308 [ERROR]: Module "./connection.ts" has already exported a member named 'RedisConnectOptions'. Consider explicitly re-exporting to resolve the ambiguity.
export * from "./redis.ts";
~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://raw.githubusercontent.com/keroxp/deno-redis/master/mod.ts:8:1
```

Tell me please, has something changed on your end, or is this my doing?

**Comment by Terkwood** [comment]
I've seen this momentarily also, while working on #86. Didn't take time to track it down...

**Comment by reselbob** [comment]
PS: here is the code in question:

`https://github.com/reselbob/denodemo/tree/master/pubbersubber`

Here is how to replicate: 

`sh pubbersubber/tests/run_tests.sh`

**Comment by Terkwood** [comment]
Thanks @uki00a! 🏁

**Comment by uki00a** [comment]
@reselbob
This issue was resolved at #107.
Please refresh your Deno cache!

**Comment by reselbob** [comment]
That fixed the first problem, but now the Bad Resource ID error is back

```
error: Uncaught BadResource: Bad resource ID 
    at unwrapResponse ($deno$/ops/dispatch_minimal.ts:63:11)
    at Object.sendAsyncMinimal ($deno$/ops/dispatch_minimal.ts:106:10)
    at async Object.read ($deno$/ops/io.ts:39:17)
    at async BufReader._fill (https://deno.land/std@v0.59.0/io/bufio.ts:85:18)
    at async BufReader.peek (https://deno.land/std@v0.59.0/io/bufio.ts:388:9)
```

**Comment by uki00a** [comment]
Hmm, can you test it using the fixed version of `deno-redis`? (https://denopkg.com/keroxp/deno-redis@v0.10.4/mod.ts)
If the same problem isn't reproduced, then it is probably introduced by #92.

**Comment by uki00a** [comment]
@reselbob I'm sorry for the delay.
That problem has been fixed in [v0.11.1](https://github.com/denolib/deno-redis/releases/tag/v0.11.1).
Please update `deno-redis` to the latest version.

**Comment by reselbob** [comment]
Thanks!
